import type { ComplianceObligation, EntityApplicability } from '@/lib/compliance/types';

const ALL: EntityApplicability = { company: true, llp: true, partnership: true, proprietorship: true };
const COMPANY_ONLY: EntityApplicability = { company: true, llp: false, partnership: false, proprietorship: false };
const LLP_ONLY: EntityApplicability = { company: false, llp: true, partnership: false, proprietorship: false };

/** Master obligations from Compliances (2) + Sheet4 — recurring calendar items only. */
export const COMPLIANCE_OBLIGATIONS: ComplianceObligation[] = [
  // Income Tax — fixed calendar
  {
    id: 'it-advance-tax-q1',
    complianceArea: 'Income Tax',
    particular: 'Advance Tax Payment Q1',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 5, day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'it-advance-tax-q2',
    complianceArea: 'Income Tax',
    particular: 'Advance Tax Payment Q2',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 8, day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'it-advance-tax-q3',
    complianceArea: 'Income Tax',
    particular: 'Advance Tax Payment Q3',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 11, day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'it-advance-tax-q4',
    complianceArea: 'Income Tax',
    particular: 'Advance Tax Payment Q4',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 2, day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'it-tds-payment',
    complianceArea: 'Income Tax',
    particular: 'TDS Payment',
    authority: 'IT',
    frequency: 'monthly',
    triggerType: 'tds_liability',
    dueRule: { kind: 'nth-day-next-month', day: 7 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'it-tds-return-q1',
    complianceArea: 'Income Tax',
    particular: 'TDS Return Filing Q1',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'tds_liability',
    dueRule: { kind: 'fixed-calendar-date', month: 6, day: 31 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },
  {
    id: 'it-tds-return-q2',
    complianceArea: 'Income Tax',
    particular: 'TDS Return Filing Q2',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'tds_liability',
    dueRule: { kind: 'fixed-calendar-date', month: 9, day: 31 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },
  {
    id: 'it-tds-return-q3',
    complianceArea: 'Income Tax',
    particular: 'TDS Return Filing Q3',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'tds_liability',
    dueRule: { kind: 'fixed-calendar-date', month: 0, day: 31 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },
  {
    id: 'it-tds-return-q4',
    complianceArea: 'Income Tax',
    particular: 'TDS Return Filing Q4',
    authority: 'IT',
    frequency: 'quarterly',
    triggerType: 'tds_liability',
    dueRule: { kind: 'fixed-calendar-date', month: 4, day: 31 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },
  {
    id: 'it-itr',
    complianceArea: 'Income Tax',
    particular: 'Income Tax Return Filing',
    authority: 'IT',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'days-after-fy-end', days: 122 },
    appliesTo: ALL,
    applicabilityNote: 'Non-audit cases — 31 Jul; audit cases later',
    penaltyRisk: 'medium',
  },
  {
    id: 'it-form-16',
    complianceArea: 'Income Tax',
    particular: 'Form 16 Issue',
    authority: 'IT',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'fixed-calendar-date', month: 5, day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },

  // GST — registration-based
  {
    id: 'gst-gstr-1',
    complianceArea: 'GST',
    particular: 'GSTR-1 Filing',
    authority: 'GST',
    frequency: 'monthly',
    triggerType: 'gst_registration',
    dueRule: { kind: 'nth-day-next-month', day: 11 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'gst-gstr-3b',
    complianceArea: 'GST',
    particular: 'GSTR-3B Filing',
    authority: 'GST',
    frequency: 'monthly',
    triggerType: 'gst_registration',
    dueRule: { kind: 'nth-day-next-month', day: 20 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'gst-gstr-9',
    complianceArea: 'GST',
    particular: 'Annual Return (GSTR-9)',
    authority: 'GST',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'fixed-calendar-date', month: 11, day: 31 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },

  // Companies Act — company only
  {
    id: 'mca-dir3-kyc',
    complianceArea: 'Companies Act, 2013',
    particular: 'Director KYC (DIR-3 KYC)',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 8, day: 30 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'high',
  },
  {
    id: 'mca-dpt-3',
    complianceArea: 'Companies Act, 2013',
    particular: 'DPT-3 Filing',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 5, day: 30 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'medium',
  },
  {
    id: 'mca-msme-1-apr',
    complianceArea: 'Companies Act, 2013',
    particular: 'MSME-1 Filing (Apr–Sep)',
    authority: 'MCA',
    frequency: 'half-yearly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 9, day: 31 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'medium',
  },
  {
    id: 'mca-msme-1-oct',
    complianceArea: 'Companies Act, 2013',
    particular: 'MSME-1 Filing (Oct–Mar)',
    authority: 'MCA',
    frequency: 'half-yearly',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 3, day: 30 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'medium',
  },
  {
    id: 'mca-aoc-4',
    complianceArea: 'Companies Act, 2013',
    particular: 'Form AOC-4',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'days-after-agm', days: 30 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'high',
  },
  {
    id: 'mca-mgt-7',
    complianceArea: 'Companies Act, 2013',
    particular: 'Form MGT-7',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'days-after-agm', days: 60 },
    appliesTo: COMPANY_ONLY,
    penaltyRisk: 'high',
  },

  // LLP Act — LLP only
  {
    id: 'llp-form-11',
    complianceArea: 'LLP Act',
    particular: 'Form 11 (Annual Return)',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'fixed-calendar-date', month: 2, day: 31 },
    appliesTo: LLP_ONLY,
    penaltyRisk: 'medium',
  },
  {
    id: 'llp-form-8',
    complianceArea: 'LLP Act',
    particular: 'Form 8 (Statement of Accounts)',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'fixed-calendar-date', month: 9, day: 30 },
    appliesTo: LLP_ONLY,
    penaltyRisk: 'medium',
  },
  {
    id: 'llp-partner-kyc',
    complianceArea: 'LLP Act',
    particular: 'Designated Partner KYC',
    authority: 'MCA',
    frequency: 'annual',
    triggerType: 'fixed_annual',
    dueRule: { kind: 'fixed-calendar-date', month: 8, day: 30 },
    appliesTo: LLP_ONLY,
    penaltyRisk: 'high',
  },

  // Labour
  {
    id: 'labour-pf-payment',
    complianceArea: 'Labour Laws',
    particular: 'EPF Return & Payment',
    authority: 'EPFO',
    frequency: 'monthly',
    triggerType: 'pf_registration',
    dueRule: { kind: 'nth-day-next-month', day: 15 },
    appliesTo: ALL,
    penaltyRisk: 'medium',
  },
  {
    id: 'labour-esi-return',
    complianceArea: 'Labour Laws',
    particular: 'ESI Return Filing',
    authority: 'ESIC',
    frequency: 'half-yearly',
    triggerType: 'esi_registration',
    dueRule: { kind: 'fixed-calendar-date', month: 4, day: 11 },
    appliesTo: ALL,
    penaltyRisk: 'low',
  },

  // FEMA
  {
    id: 'fema-fla',
    complianceArea: 'FEMA / RBI',
    particular: 'FLA Return',
    authority: 'RBI',
    frequency: 'annual',
    triggerType: 'fy_end',
    dueRule: { kind: 'fixed-calendar-date', month: 6, day: 15 },
    appliesTo: ALL,
    isConditional: true,
    applicabilityNote: 'Foreign Investment',
    penaltyRisk: 'medium',
  },
];

export function obligationApplies(
  obligation: ComplianceObligation,
  entityLegalForm: keyof EntityApplicability,
): boolean {
  return obligation.appliesTo[entityLegalForm] === true;
}
